[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_microros_transport = serial ; Use 'wifi' if you prefer
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio.git
build_flags =
    -DESP_PLATFORM
    -DIDF_VER=\"v0.0.0\"